### ISSUE TITLE
git tags and history appear out of order

### ISSUE THREAD

**Issue by disaac** [unifio/covalence#62]
There is a currently an issue with the tag references in the unifio/covalence repository. There is a 0.7.4 tag and a v0.7.4 tag that point to different times in history. I encountered an error when trying to address [issue#54 "Git LFS pointers are incorrect in history"](https://github.com/unifio/covalence/issues/54) as shown below: 

```bash
$ git lfs migrate import --include=images/*
migrate: Fetching remote refs: ..., done
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/tags/origin/0.7.4'
```

When viewing the reference in github the history on the version numbers and tags seems out of order as shown below: 
![screenshot_3932](https://user-images.githubusercontent.com/15255373/40432326-48fbc45a-5e5e-11e8-9241-b7920193af3c.png)

**Comment by yuhunglin** [comment]
@disaac suggestions on a fix?

Also if we automate the release process via something like `ghr` might be able to avoid lots of issues with human errors. Was wondering we we could get something that collected up all the git commit comments between tags automatically as a release comment though.

**Comment by disaac** [comment]
* Deleted release 0.7.4 69d12dd9 
* v0.7.4 still comes after v0.7.6 but since it is a release that might be referenced going to leave out of order since others may be referencing the tag. In order to properly correct the versioning to be in the proper release order it would require making 69d12dd9 the v0.7.4 and incrementing every version after which would be a mess. 
* Closing out ticket and leaving out of order will create a new ticket for tracking an automated release process to avoid such human error in the future as mentioned by @yuhunglin
